### ISSUE TITLE
Pinyin tone accents to numbers?

### ISSUE THREAD

**Issue by mklnz** [plexus/ting#4]
I have gotten numbers -> accents to work, but does this gem go the reverse way as well?
I tried:

```
reader = Ting.reader(:hanyu, :accents)
reader.parse("sànbù")
Ting::ParseError: Parsing of "sànbù" failed : Can't parse `"sanbù"'
    from /Users/michael/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ting-0.9.0/lib/ting/reader.rb:21:in `rescue in parse'
    from /Users/michael/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ting-0.9.0/lib/ting/reader.rb:11:in `parse'
    from (irb):6
```

Edit:
Oh I see, it requires the pinyin to be space delimited. Is it possible to parse pinyin without spaces in them?

**Comment by jlnr** [comment]
The HanyuPinyinParser seems to be too aggressive about erhua.

```
irb(main):001:0> Ting::HanyuPinyinParser.new.parse("suīrán")
=> [[<Ting::Syllable <initial=Si, final=Ui, tone=1>>], [<Ting::Syllable <initial=Empty, final=Er, tone=5>>], [<Ting::Syllable <initial=Empty, final=An, tone=2>>]]
=> [[<Ting::Syllable <initial=Empty, final=Iang, tone=2>>], [<Ting::Syllable <initial=Empty, final=Er, tone=5>>], [<Ting::Syllable <initial=Empty, final=Ou, tone=4>>]]
```

Hacktoberfest time!! 😅

**Comment by plexus** [comment]
Always warms my heart to see some activity on this project. My first open source project, started over a decade ago <3

Good luck improving the parser!
